import Image from "next/image";
import styles from "./page.module.css";
import Link from "next/link";
import { ThemeToggle } from "@/components/ui/ThemeToggle";
import { MoreDropdown } from "@/components/ui/MoreDropdown";
import { ImageUploader } from "@/components/upload/ImageUploader";
import { SampleImages } from "@/components/upload/SampleImages";
import { SeoContent } from "@/components/home/SeoContent";

export default function Home() {
  return (
    <div className={styles.container}>
      <header className={styles.header}>
        <div className={styles.logo}>
          <img src="/logo.png" alt="photext.ai logo" style={{ height: '32px', width: 'auto' }} />
        </div>
        <nav className={styles.nav}>
          <Link href="/edit-text-in-image">Edit Text</Link>
          <Link href="/remove-text-from-image">Remove Text</Link>
          <Link href="/remove-background-from-image">Remove BG</Link>
          <Link href="/change-image-background">Background Changer</Link>
          <Link href="/guides">Guides</Link>
          <Link href="/identify-fonts">Identify Fonts</Link>
          <MoreDropdown />
          <ThemeToggle />
        </nav>
      </header>

      <main className={styles.main}>
        <section className={styles.hero}>
          <h1 className={styles.h1}>Edit Text in Image Online with AI</h1>
          <p className={styles.subtitle}>
            Instantly replace, remove, or change text in any photo, screenshot, or graphic. No design skills required.
          </p>
          
          <div className={styles.uploadArea}>
            <ImageUploader />
            <SampleImages />
          </div>
        </section>

        <SeoContent />
      </main>

      <footer className={styles.footer}>
        <p>&copy; 2026 photext.ai. All rights reserved.</p>
        <p style={{ marginTop: '0.5rem', fontSize: '0.875rem', color: 'var(--text-secondary)' }}>
          Generated by <a href="https://www.sntechweb.com/" target="_blank" rel="noopener noreferrer" style={{ color: 'var(--accent-primary)', textDecoration: 'none' }}>SN Tech</a>
        </p>
      </footer>
    </div>
  );
}
