"use client";

import React from "react";
import { EditorLayout } from "@/components/editor/EditorLayout";
import { ImageUploader } from "@/components/upload/ImageUploader";
import { useEditorStore } from "@/lib/store/editorStore";

interface ToolPageClientProps {
  title: string;
  description: string;
}

export function ToolPageClient({ title, description }: ToolPageClientProps) {
  const { originalImage } = useEditorStore();

  if (originalImage) {
    return <EditorLayout />;
  }

  return (
    <div style={{ minHeight: '80vh', display: 'flex', flexDirection: 'column' }}>
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', padding: '4rem 2rem', textAlign: 'center', maxWidth: '800px', margin: '0 auto', width: '100%' }}>
        <h1 style={{ fontSize: '2.5rem', marginBottom: '1rem', fontWeight: 800 }}>{title}</h1>
        <p style={{ marginBottom: '3rem', fontSize: '1.2rem', color: 'var(--text-secondary)' }}>
          {description}
        </p>
        <ImageUploader redirectPath="" />
      </div>
      
      <footer style={{ padding: '2rem', textAlign: 'center', borderTop: '1px solid var(--border-color)', width: '100%' }}>
        <p style={{ fontSize: '0.875rem', color: 'var(--text-secondary)' }}>&copy; 2026 photext.ai. All rights reserved.</p>
        <p style={{ marginTop: '0.5rem', fontSize: '0.875rem', color: 'var(--text-secondary)' }}>
          Generated by <a href="https://www.sntechweb.com/" target="_blank" rel="noopener noreferrer" style={{ color: 'var(--accent-primary)', textDecoration: 'none' }}>SN Tech</a>
        </p>
      </footer>
    </div>
  );
}
