import React from 'react';
import Link from 'next/link';
import { ThemeToggle } from '@/components/ui/ThemeToggle';
import { MoreDropdown } from '@/components/ui/MoreDropdown';
import styles from '@/app/page.module.css';

export function PlaceholderPage({ title }: { title: string }) {
  return (
    <div className={styles.container}>
      <header className={styles.header}>
        <div className={styles.logo}>
          <Link href="/" style={{ display: 'flex', alignItems: 'center', textDecoration: 'none' }}>
            <img src="/logo.png" alt="photext.ai logo" style={{ height: '32px', width: 'auto' }} />
          </Link>
        </div>
        <nav className={styles.nav}>
          <Link href="/change-image-background">Background Changer</Link>
          <Link href="/guides">Guides</Link>
          <Link href="/identify-fonts">Identify Fonts</Link>
          <MoreDropdown />
          <ThemeToggle />
        </nav>
      </header>
      
      <main className={styles.main}>
        <section className={styles.hero}>
          <h1 className={styles.h1}>{title}</h1>
          <p className={styles.subtitle}>This feature is currently under development. Check back soon!</p>
        </section>
      </main>
      
      <footer className={styles.footer}>
        <p>&copy; 2026 photext.ai. All rights reserved.</p>
        <p style={{ marginTop: '0.5rem', fontSize: '0.875rem', color: 'var(--text-secondary)' }}>
          Generated by <a href="https://www.sntechweb.com/" target="_blank" rel="noopener noreferrer" style={{ color: 'var(--accent-primary)', textDecoration: 'none' }}>SN Tech</a>
        </p>
      </footer>
    </div>
  );
}
